WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.5.80:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/jongjetw/Projects/CloudNative/nd064_course_1-main/exercises/python-helloworld/app.py", line 9, in hello
    app.loger.info('Main request successfull')
AttributeError: 'Flask' object has no attribute 'loger'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2021 14:00:08] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/jongjetw/Projects/CloudNative/nd064_course_1-main/exercises/python-helloworld/app.py", line 9, in hello
    app.loger.info('Main request successfull')
AttributeError: 'Flask' object has no attribute 'loger'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2021 14:00:21] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2021 14:00:22] "[32mGET  HTTP/1.1[0m" 308 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/jongjetw/Projects/CloudNative/nd064_course_1-main/exercises/python-helloworld/app.py", line 9, in hello
    app.loger.info('Main request successfull')
AttributeError: 'Flask' object has no attribute 'loger'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2021 14:00:22] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/jongjetw/Projects/CloudNative/nd064_course_1-main/exercises/python-helloworld/app.py", line 9, in hello
    app.loger.info('Main request successfull')
AttributeError: 'Flask' object has no attribute 'loger'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2021 14:00:25] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/jongjetw/Projects/CloudNative/nd064_course_1-main/exercises/python-helloworld/app.py", line 9, in hello
    app.loger.info('Main request successfull')
AttributeError: 'Flask' object has no attribute 'loger'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2021 14:00:39] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:app:Exception on /status [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/jongjetw/Projects/CloudNative/nd064_course_1-main/exercises/python-helloworld/app.py", line 20, in healthcheck
    app.loger.info('Status request successfull')
AttributeError: 'Flask' object has no attribute 'loger'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2021 14:00:39] "[35m[1mGET /status HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.5.80:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on /status [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/jongjetw/Projects/CloudNative/nd064_course_1-main/exercises/python-helloworld/app.py", line 20, in healthcheck
    app.loger.info('Status request successfull')
AttributeError: 'Flask' object has no attribute 'loger'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2021 14:00:56] "[35m[1mGET /status HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.5.80:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on /status [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/jongjetw/Projects/CloudNative/nd064_course_1-main/exercises/python-helloworld/app.py", line 20, in healthcheck
    app.loger.info('Status request successfull')
AttributeError: 'Flask' object has no attribute 'loger'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2021 14:01:44] "[35m[1mGET /status HTTP/1.1[0m" 500 -
ERROR:app:Exception on /status [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/jongjetw/Projects/CloudNative/nd064_course_1-main/exercises/python-helloworld/app.py", line 20, in healthcheck
    app.loger.info('Status request successfull')
AttributeError: 'Flask' object has no attribute 'loger'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2021 14:01:45] "[35m[1mGET /status HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.5.80:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on /status [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/jongjetw/Projects/CloudNative/nd064_course_1-main/exercises/python-helloworld/app.py", line 20, in healthcheck
    app.loger.info('Status request successfull')
AttributeError: 'Flask' object has no attribute 'loger'
INFO:werkzeug:127.0.0.1 - - [26/Jun/2021 14:02:31] "[35m[1mGET /status HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.5.80:5000/ (Press CTRL+C to quit)
INFO:app:Status request successfull
INFO:werkzeug:127.0.0.1 - - [26/Jun/2021 14:02:57] "GET /status HTTP/1.1" 200 -
INFO:app:Status request successfull
INFO:werkzeug:127.0.0.1 - - [26/Jun/2021 14:03:03] "GET /status HTTP/1.1" 200 -
INFO:app:Main request successfull
INFO:werkzeug:127.0.0.1 - - [26/Jun/2021 14:03:04] "GET / HTTP/1.1" 200 -
INFO:app:Main request successfull
INFO:werkzeug:127.0.0.1 - - [26/Jun/2021 14:03:07] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [26/Jun/2021 14:03:11] "[33mGET /matrics HTTP/1.1[0m" 404 -
INFO:app:Matrics request successfull
INFO:werkzeug:127.0.0.1 - - [26/Jun/2021 14:03:16] "GET /metrics HTTP/1.1" 200 -
